### ISSUE TITLE
python2.7 - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by arthurlutz** [panyanyany/beeprint#26]
```
python run.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
../skin/default/truetype/VarelaRound-Regular.ttf
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    from UI.main_screen  import MainScreen
  File "/home/arthur/local/clockworkpi/launcher/sys.py/UI/main_screen.py", line 14, in <module>
    from beeprint import pp
  File "/home/arthur/.virtualenvs/launcher/local/lib/python2.7/site-packages/beeprint/__init__.py", line 1, in <module>
    from .printer import pp
  File "/home/arthur/.virtualenvs/launcher/local/lib/python2.7/site-packages/beeprint/printer.py", line 25, in <module>
    from .models.block import Block, Context
  File "/home/arthur/.virtualenvs/launcher/local/lib/python2.7/site-packages/beeprint/models/block.py", line 717
    def rearrenge(self, ctx: Context, typ, wrapper):
                           ^
SyntaxError: invalid syntax
```

**Comment by panyanyany** [comment]
sorry about that. it fix now.

**Comment by arthurlutz** [comment]
Any idea when this fix will arrive on a published version on pypi ?

**Comment by panyanyany** [comment]
Well, I have published to pypi. Just try it.
