### ISSUE TITLE
Beeprint pp  fails when printing Objects (Python 3)

### ISSUE THREAD

**Issue by dezoito** [panyanyany/beeprint#7]
I am trying to use beeprint to debug Django objects, such as models and responses.

Here's an example of how it is failing:

I have a very simple test for a view:

```python
 def test_default_index_view(self):
        response = self.client.get(reverse('index'), follow=True) # redirects
        pp(response)
        self.assertEqual(response.status_code, 200)
```

pprint would return `<django.template.response.TemplateResponse object at 0x7f814d62b1d0>`

pp returns the error message below:

Traceback (most recent call last):
  File "/vagrant/app/main/tests/testing_utilities.py", line 25, in run
    method(*args, **kw)
  File "/vagrant/app/main/tests/unit/test_views_using_client.py", line 36, in test_default_index_view
    pp(response)
  File "/usr/local/lib/python3.4/dist-packages/beeprint/printer.py", line 35, in pp
    res = str(Block(config, Context(obj=o)))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 123, in build_block
    ret += str(ClassBlock(self.config, self.ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 238, in build_block
    ret += str(PairBlock(self.config, ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 467, in build_block
    ret += str(Block(self.config, ctx)) + ustr(tail + block_ending)
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 117, in build_block
    ret += str(ListBlock(self.config, self.ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 347, in build_block
    ret += str(Block(self.config, ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 123, in build_block
    ret += str(ClassBlock(self.config, self.ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 238, in build_block
    ret += str(PairBlock(self.config, ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 467, in build_block
    ret += str(Block(self.config, ctx)) + ustr(tail + block_ending)
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 123, in build_block
    ret += str(ClassBlock(self.config, self.ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 238, in build_block
    ret += str(PairBlock(self.config, ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 467, in build_block
    ret += str(Block(self.config, ctx)) + ustr(tail + block_ending)
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 120, in build_block
    ret += str(TupleBlock(self.config, self.ctx))
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 36, in __str__
    return self.build_block()
  File "/usr/local/lib/python3.4/dist-packages/beeprint/models/block.py", line 400, in build_block
    indent=indent_cnt + 1,
TypeError: __init__() got an unexpected keyword argument 'position'

**Comment by panyanyany** [comment]
sorry for that. 
please install newest version of 2.4.1. 
i think it's OK now.

**Comment by dezoito** [comment]
Thank you for the effort and please don't take my post as negative criticism...

**Comment by panyanyany** [comment]
> please don't take my post as negative criticism

sorry, what does it mean ? have I do something wrong ?  please tell me what happened ...

**Comment by dezoito** [comment]
What I meant is that I was not complaining about the error messages, but just trying to make you aware of the problem.

You did nothing wrong and I appreciate the effort you put in fixing the issue right away :)
